---
title: "Error with Euler method"
author: "Alfonso R. Reyes"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Error with Euler method}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Given the differential equation:

$$ \frac {dy} {dx} = x + y $$

Use the Euler ODE solver to find the error between the exact solution given by:

$$ y(x) = e^e - x - 1$$

at these step sizes: 1, 0.5, 0.25, 0.1, 0.01, 0.001, 0.0001; and plot the the step size versus the error when the $x = 1$.

## Build the ODE solver

```{r message=FALSE, results="hold"}
library(rODE)

setClass("EulerError", slots = c(
    stack = "environment"           # environment object inside the class
    ),
    contains = c("ODE")
    )

setMethod("initialize", "EulerError", function(.Object, ...) {
    .Object@stack$n <-  0               # "n" belongs to the class environment
    .Object@state   <- vector("numeric", 1)
    return(.Object)
})

setMethod("getExactSolution", "EulerError", function(object, t, ...) {
    # analytical solution
    return(exp(t) - t - 1)
})

setMethod("getState", "EulerError", function(object, ...) {
    object@state
})

setMethod("getRate", "EulerError", function(object, state, ...) {
    object@rate[1] <- state[1] + state[2]      # x + y
    object@rate[2] <- 1                        # dx/dx
    object@stack$n <- object@stack$n + 1       # add 1 to the rate count
    object@rate
})

# constructor
EulerError <- function(y) {
    .EulerError <- new("EulerError")
    .EulerError@state[1] = y        # y 
    .EulerError@state[2] = 0        # x = t
    return(.EulerError)
}
```

```{r}
# class implementation
EulerErrorApp <- function(verbose = FALSE) {
    initial_y <- 0
    xmax      <- 1
    stepSize  <- 0.01
    n_steps   <- as.integer((xmax + stepSize / 2) / stepSize)
    
    ode        <- EulerError(initial_y)
    ode_solver <- Euler(ode)
    ode_solver <- setStepSize(ode_solver, stepSize)
    
    cat(sprintf("%10s %14s %14s %5s \n", "x", "y", "TrueY", "n"))   # header
    steps <- 0
    while (steps < n_steps) {
        ode_solver <- step(ode_solver)
        state      <- getState(ode_solver@ode)
        steps      <- ode_solver@ode@stack$n
        if (verbose)
            cat(sprintf("%10f %14e %14e %5d \n",
            # cat(sprintf("%10f %14e %5d \n",                         
                        state[2],     # x = t
                        state[1],     # y
                        # state[1] - getExactSolution(ode_solver@ode, time),
                        getExactSolution(ode_solver@ode, state[2]),
                        steps))
    }
    cat("rate steps evaluated #", steps)
}

EulerErrorApp(verbose = TRUE)
```

